spring.application.name=hospitalManagement


#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital
spring.datasource.username=postgres
spring.datasource.password=Random123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true






jwt.secretKey=ghjgjkgguigh1213iughjkhjh1213ukg3kjh3h32h3jkhjk3hk2h3h3jkh23


#adminDetails

admin.username=adminHussain
admin.password=@dmin777
admin.email=admin777@.pollo
